def COLOR_MAP = [
    'FAILURE' : 'danger',
    'SUCCESS' : 'good'
]
pipeline{
    agent any
    tools{
        jdk 'jdk17'
        maven 'maven3'
    }
    stages {
        stage('Checkout From Git'){
            steps{
                git branch: 'develop', url: 'https://github.com/saif33BA/devops.git'
            }
        }
        stage('mvn compile'){
            steps{
                sh 'mvn clean compile'
            }
        }
        stage('mvn test'){
            steps{
                sh 'mvn test -DskipTests=true'
            }
        }
    }
}